### PR TITLE
Upgraded to Angular 5.0.3 and added metadata publishing for npm packa…

### PR DESCRIPTION
**Pull request by Bidthedog**
…ge to make compatible with angular cli

Please test fully before publishing!

### CODE REVIEW

**Comment by Bidthedog** [comment]
Hopefully fixes #9

**Comment by Bidthedog** [comment]
@abhazelton I've added a commit to this PR that I think may fix the issue. Can you test and check please? As per #9

**Comment by inklingsofreality** [comment]
I can confirm that this PR fixes the AOT compilation issue. Thanks @Bidthedog. I'm having to keep a local version of this so that I can continue to use this in my main build, until this gets pushed.

**Comment by jonlejon** [comment]
bump - any chance this PR can get merged?

**Comment by abhazelton** [comment]
Sorry for the delay guys, I've pushed the PR, so please give that a try.

**Pull request merged**
