### PR TITLE
TSLint Fixes

### PR DESCRIPTION
**Pull request by Bidthedog**
- Updated all dependencies and packages
- Removed a number of deprecated / obsolete tslint rules
- Fixed linting issues in .ts files
- Reorganised npm scripts - new "build" and "lint" commands now available

Seems to work fine for me now, locally at least.

### CODE REVIEW

**Comment by Bidthedog** [comment]
FYI, I get errors when trying to link this to my project locally - can't say I've tried referencing an Angular package locally before, so I'm not sure if I'm doing something wrong, but I imagine this will work fine when published. Here's what I've done to test it:

```
cd F:\Git\animate-on-scroll
npm link

cd F:/Git/ShadowMosesWebsite/src/ShadowMoses.Web/
npm link ng2-animate-on-scroll

yarn start
```

Get the following error:

> ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in F:/Git/ShadowMosesWebsite/src/ShadowMoses.Web/node_modules/ng2-animate-on-scroll/node_modules/@angular/core/core.d.ts, resolving symbol AnimateOnScrollModule in F:/Git/ShadowMosesWebsite/src/ShadowMoses.Web/node_modules/ng2-animate-on-scroll/index.ts, resolving symbol AnimateOnScrollModule in F:/Git/ShadowMosesWebsite/src/ShadowMoses.Web/node_modules/ng2-animate-on-scroll/index.ts
>     at positionalError (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:25266:35)
>     at simplifyInContext (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:25109:27)
>     at StaticReflector.simplify (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:25123:13)
>     at StaticReflector.annotations (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24553:41)
>     at _getNgModuleMetadata (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
>     at _extractLazyRoutesFromStaticModule (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
>     at F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
>     at Array.reduce (native)
>     at _extractLazyRoutesFromStaticModule (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
>     at Object.listLazyRoutesOfModule (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
>     at Function.NgTools_InternalApi_NG_2.listLazyRoutes (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
>     at AotPlugin._getLazyRoutesFromNgtools (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:207:44)
>     at _donePromise.Promise.resolve.then.then.then.then.then (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:443:24)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> 
> webpack: Failed to compile.

**Comment by Bidthedog** [comment]
Interestingly, I also get this error when I roll back to your last commit - so I think I'm just doing something wrong when trying to link locally.

**Comment by abhazelton** [comment]
Thanks @Bidthedog, have merged the fix.  Also updated the [test project](https://github.com/abhazelton/animate-on-scroll-test) and all seems to work fine.

**Comment by Bidthedog** [comment]
Excellent, I'll upgrade to the latest version ASAP and test.

**Pull request merged**
